baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tom's Hugo Site"
theme = "hugo-coder"



[params]
hideCopyright = true
hideCredits = true
colorScheme = "auto"
author = "Thomas Johander"
info = "Software Engineer"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/lopan455/"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Posts"
url = "/posts/"
weight = 3

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 4